# Setup
title:        小旭旭的个人博客
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      "https://zhangzexu.github.io/"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       zhangzexu
  url:        https://zhangzexu.github.io/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
