# Setup
title:        小旭旭的个人博客
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       zhangzexu
  url:        zhangzexu.github.io

# Gems
gems:
- jekyll-paginate

#Others
markdown: kramdown

#gitalk settings
gitalk:
  enable: true #用来做启用判断可以不用
  owner: zhangzexu
  repo:  zhangzexu.github.io
  admin: zhangzexu
  clientID: 8bb21c31f4b8beb9587c
  clientSecret: eb4266e40f753dab3389a96783a7517a3bc6235f

